---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

#### Jianing Liu 

### Address and Contant Info
60 Haven Ave, APT 10C, NY, 10032 jl6325@cumc.columbia.edu / 217-721-8486 

### Educational Background 

##### Columbia University Expected Graduation,                                 May 2024

- Master of Science in Epidemiology,                        New York, United States 


##### Muskingum University,                                           Aug 2021–May 2022

- Bachelor of Arts in Public Health,                            Ohio, United States

- GPA: 3.983 / 4.0 
  
- President’s List 202, Dean’s List in 2022, and International Student Scholarship 
  

##### North China Institute of Science and Technology,              Sept 2018–June 2022 

- Bachelor of Engineering in Safety Engineering,                       Hebei, China 

- 3+1 Dual Degree, Cooperative & Transfer Educational Program 

### Certifications & Skills 
##### Technical skills: 

- Proficiency in using Microsoft Office, Google Suite, R, and SAS 
  
##### Certification: 

- GOOD CLINICAL PRACTICE (NIDA Clinical Trials Network Certificate of Completion) Jul 2023 
  
### Research Experience 

#### Key Research and Development Program of China: 

##### Research on Construction of Anti-food Fraud Database and Vulnerability Assessment of Whole Food Chain, No.2017YFC1601701. 

- Research Member, North China Institute of Science and Technology, Sept 2018–June 2022 

- Responsible for building a food chain model based on collected data in addition to data analysis by R. 
  
- Established a vulnerability assessment index system for different food types in China through data collection, review, and establishment of food chain models. 
  
##### Investigation of Accidental Death of College Students in the Past Ten Years 

- Research Member, North China Institute of Science and Technology, June 2021- Aug 2021 

- Responsible for the data collection, integration, and statistics, investigating the causes and trends of death, and analysis of the data and information. 
  
- Assisted in data combining for the purpose of advising on prevention and control of unexpected deaths of college students. 
  
### Work Experience 

#### Zhejiang Jingxin Pharmaceutical Co., Ltd. (Inner Mongolia Branch) 

- Data Quality Analyst Intern,                                   Jul 2023- Aug 2023 

- Responsible for collecting and analyzing data using Excel, comparing product data with quality inspection standards, checking product pass rate, and following the instructor to monitor, prevent, and provide corrective actions. 
  
#### MeDomino Insights 

- Part-time,                                                   June 2023- June 2023 

- Responsible for accessing the official website to collect the number of beds, number of doctors and number of Rehabilitation Physicians in the Rehabilitation Department based on the list of hospitals provided by the client and collecting and organizing the data using Microsoft Excel. 

#### Hangjinhouqi Center for Disease Control and Prevention 

- Data Analytic Intern,                                           Jul 2021–Aug 2021 

- Conducted local epidemiological surveys during COVID-19 outbreak period. 
  
-  Analyzed data using Excel and SAS software for statistics and created epidemic distribution maps. 
  
-  Participated and helped to establish prevention measures and management policies. 
  
#### Shanghai Huining Culture Co. 
- Intern,                                                         Dec 2019–Jan 2020 

- Responsible for the tallying of student scores for each group in the arena and visualizing the results.
  
- Assistant tutors to assist with student management and guidance